SCR_EditorAttributeCategory {
 m_UIInfo SCR_UIInfo "{689EE7B54AE08379}" {
  Name "DarcChopper"
  Description "AI piloted helicopters"
  Icon "{03392FD8BD19DE62}UI/Textures/Icons/gm_mission_Chopper_round.edds"
 }
 m_iPriority 80
}