SCR_PlaceableEntitiesRegistry {
 m_Prefabs +{
  "{5678893357C6FC10}Prefabs/Vehicles/Helicopters/Mi8MT/Mi8MT_armed_gunship_HE_Patrol.et"
  "{3815F0A6CA3FF790}Prefabs/Vehicles/Helicopters/Mi8MT/Mi8MT_armed_gunship_HEDP_Patrol.et"
  "{5BBDA2DACF9CDCA4}Prefabs/Vehicles/Helicopters/Mi8MT/Mi8MT_unarmed_transport_Patrol.et"
  "{446634BB04ED3705}Prefabs/Vehicles/Helicopters/UH1H/SP02_GUNSHIP_Patrol.et"
  "{8FD9275E605A1A93}Prefabs/Vehicles/Helicopters/UH1H/UH1H_armed_gunship_HE_Patrol.et"
  "{4CFDE3580182C452}Prefabs/Vehicles/Helicopters/UH1H/UH1H_armed_gunship_HEDP_sharkNose_Patrol.et"
  "{96D1D7E22C123DEE}Prefabs/Vehicles/Helicopters/UH1H/UH1H_armed_Patrol.et"
  "{9902F419417C00AA}Prefabs/Vehicles/Helicopters/UH1H/UH1H_sharkNose_Transport_Patrol.et"
  "{B9CFB73A28AF217A}Prefabs/Vehicles/Helicopters/Mi8MT/Mi8MT_armed_gunship_HEDP_Patrol_FIA.et"
  "{CD4EA91AC53CBCC4}Prefabs/Vehicles/Helicopters/Mi8MT/Mi8MT_armed_gunship_HE_Patrol_FIA.et"
  "{774E9DA8AF02F8DA}Prefabs/Vehicles/Helicopters/UH1H/SP02_GUNSHIP_Patrol_FIA.et"
  "{FA51AC2732EEF395}Prefabs/Vehicles/Helicopters/UH1H/UH1H_armed_Patrol_FIA.et"
  "{435F663B9456C29E}Prefabs/Vehicles/Helicopters/UH1H/UH1H_civ_livery_v1_Patrol.et"
  "{896B241CB1BB3DFF}Prefabs/Vehicles/Helicopters/Mi8MT/Mi8MT_armed_gunship_HE_Patrol_Friend.et"
  "{E7065D892C42367F}Prefabs/Vehicles/Helicopters/Mi8MT/Mi8MT_armed_gunship_HEDP_Patrol_Friend.et"
  "{E6FFDEDA4DFC9CB4}Prefabs/Vehicles/Helicopters/UH1H/SP02_GUNSHIP_Patrol_Friend.et"
  "{115A5D74B2910B9B}Prefabs/Vehicles/Helicopters/UH1H/UH1H_armed_gunship_HE_Patrol_Friend.et"
 }
}