SCR_MapConfig {
 m_aUIComponents {
  SDRC_MapStoryUI "{66353C82291438CB}" {
   m_fRulerLength 600
   m_sRootWidgetName "StoryFrame"
   m_sImageWidgetName "StoryImage"
   m_sToolMenuIconName "unused variable"
   m_aSizesArray {
    1
   }
  }
 }
 m_bEnableLegendScale 0
 m_bEnableGrid 0
}