ActionManager {
 Contexts {
  ActionContext MapContext {
   Actions {
    Action MapMarkerDelete {
     InputSource InputSourceSum "{5D287E8398916767}" {
      Sources {
       InputSourceValue "{5D287E839D272DD3}" {
       }
      }
     }
    }
    Action SDRCMapNonValidAreaDecrease {
     Type AnalogRelative
     InputSource InputSourceSum "{685A858B5096E90D}" {
      Sources {
       InputSourceCombo "{685C8EE53A9C3E99}" {
        Sources {
         InputSourceValue "{685C8EE5237D4420}" {
          Input "keyboard:KC_LCONTROL"
          Filter InputFilterHold "{685C8EE695EDBAE4}" {
           HoldDuration 200
          }
         }
         InputSourceValue "{685C8EE5DCBEA977}" {
          Input "mouse:wheel-"
          Filter InputFilterValue "{685C8EE631432886}" {
          }
         }
        }
       }
      }
     }
    }
    Action SDRCMapNonValidAreaIncrease {
     Type AnalogRelative
     InputSource InputSourceSum "{685C8EE1926F76B5}" {
      Sources {
       InputSourceCombo "{685C8EE1926F67D4}" {
        Sources {
         InputSourceValue "{685C8EE1926F67DC}" {
          Input "keyboard:KC_LCONTROL"
          Filter InputFilterHold "{685C8EE1926F67E6}" {
           HoldDuration 200
          }
         }
         InputSourceValue "{685C8EE1926F67EA}" {
          Input "mouse:wheel+"
          Filter InputFilterValue "{685C8EE1926F67EE}" {
          }
         }
        }
       }
      }
     }
    }
   }
   ActionRefs +{
    "MapToggleShowSettings"
   }
  }
 }
}