SCR_PlaceableEntitiesRegistry {
 m_Prefabs +{
  "{DACB28E580AA22EC}Prefabs/System/DarcMissionOccupation.et"
  "{A3299C761A9B2EA4}Prefabs/System/DarcMissionPatrol.et"
  "{5CB2D5C0A1519D1B}Prefabs/System/DarcMissionConvoy.et"
  "{7E0E561D682C130F}Prefabs/System/DarcMissionHunters.et"
  "{A6EC23F8EFE0FA02}Prefabs/System/DarcMissionCrashsite.et"
 }
}