SCR_PlaceableEntitiesRegistry {
 m_Prefabs +{
  "{DACB28E580AA22EC}Prefabs/Systems/DarcMissionOccupation.et"
  "{A3299C761A9B2EA4}Prefabs/Systems/DarcMissionPatrol.et"
  "{1CCF5979C8488F09}Prefabs/Systems/DarcMissionSquatters.et"
  "{7E0E561D682C130F}Prefabs/Systems/DarcMissionHunters.et"
  "{A6EC23F8EFE0FA02}Prefabs/Systems/DarcMissionCrashsite.et"
  "{CE7D07A8484A1DE9}Prefabs/Systems/DarcMissionConvoy.et"
  "{F1BE2D46F0949F6C}Prefabs/Systems/DarcMissionRoadblock.et"
  "{6A859F436655EEF9}Prefabs/Systems/DarcMissionHvtVip.et"
  "{B9D6798E6A963E0C}Prefabs/Systems/DarcMissionHvtItem.et"
 }
}