SCR_PlaceableEntitiesRegistry {
 m_Prefabs +{
  "{DACB28E580AA22EC}Prefabs/EffectsModuleEntities/DarcMissionOccupation.et"
  "{A3299C761A9B2EA4}Prefabs/EffectsModuleEntities/DarcMissionPatrol.et"
  "{5CB2D5C0A1519D1B}Prefabs/EffectsModuleEntities/DarcMissionConvoy.et"
  "{7E0E561D682C130F}Prefabs/EffectsModuleEntities/DarcMissionHunters.et"
  "{A6EC23F8EFE0FA02}Prefabs/EffectsModuleEntities/DarcMissionCrashsite.et"
  "{1CCF5979C8488F09}Prefabs/EffectsModuleEntities/DarcMissionSquatters.et"
 }
}