SCR_EditableEntityCore {
 m_EntityLabels {
  SCR_EditableEntityCoreLabelSetting "{689EE7B5E082DE79}" {
   m_Info SCR_UIInfo "{689EE7B5E082D9D9}" {
    Name "DarcChopper"
    Description "Selection of DarcChoppers"
    Icon "{03392FD8BD19DE62}UI/Textures/Icons/gm_mission_Chopper_round.edds"
   }
   m_LabelType ENTITYTYPE_DARCCHOPPER
   m_LabelGroupType ENTITYTYPE
  }
 }
}