SCR_PlaceableEntitiesRegistry {
 m_Prefabs +{
  "{94CBD8C3721DB74B}Prefabs/Drones/DJIBase/DJI81Dropper_Darc.et"
  "{868532DB015A0DFD}Prefabs/Drones/DJIBase/DJI82Dropper_Darc.et"
  "{E6954AB05C1F7383}Prefabs/Drones/DJIBase/DJIM14Dropper_Darc.et"
  "{5B1EEBAF1FBA190E}Prefabs/Drones/DJIBase/DJIM15Dropper_Darc.et"
  "{629BE1C43E0A2E8C}Prefabs/Drones/FPVBase/FPV_OFCP_Darc.et"
  "{E9D96CD73D5A2F63}Prefabs/Drones/FPVBase/FPV_OG7V_Darc.et"
  "{849376E231AE962E}Prefabs/Drones/FPVBase/FPVRpg_Darc.et"
 }
}