SCR_PlaceableEntitiesRegistry {
 m_Prefabs +{
  "{94CBD8C3721DB74B}Prefabs/Drones/DJIBase/DJI81Dropper_Darc.et"
  "{868532DB015A0DFD}Prefabs/Drones/DJIBase/DJI82Dropper_Darc.et"
  "{E6954AB05C1F7383}Prefabs/Drones/DJIBase/DJIM14Dropper_Darc.et"
  "{5B1EEBAF1FBA190E}Prefabs/Drones/DJIBase/DJIM15Dropper_Darc.et"
 }
}