SCR_PlaceableEntitiesRegistry {
 m_sAddon "Darc Chopper"
 m_sSourceDirectory "{79DD690A0F239399}Prefabs/Systems"
 m_Prefabs {
  "{5678893357C6FC10}Prefabs/Vehicles/Helicopters/Mi8MT/Mi8MT_armed_gunship_HE_Patrol.et"
 }
}