SCR_PlaceableEntitiesRegistry {
 m_sAddon "DarcChopper"
 m_sSourceDirectory "{6C17543D6F20A778}Prefabs/Vehicles/Helicopters"
 m_Prefabs {
  "{5678893357C6FC10}Prefabs/Vehicles/Helicopters/Mi8MT/Mi8MT_armed_gunship_HE_Patrol.et"
  "{3815F0A6CA3FF790}Prefabs/Vehicles/Helicopters/Mi8MT/Mi8MT_armed_gunship_HEDP_Patrol.et"
  "{5BBDA2DACF9CDCA4}Prefabs/Vehicles/Helicopters/Mi8MT/Mi8MT_unarmed_transport_Patrol.et"
 }
}