SCR_EditableEntityCore {
 m_EntityLabels {
  SCR_EditableEntityCoreLabelSetting "{65852D09F52A0B03}" {
   m_Info SCR_UIInfo "{65852D09F1CDCECE}" {
    Name "DarcMissions"
    Description "Selection of DarcMissions"
    Icon "{16296D7B325A094B}UI/Textures/Icons/gm_mission_X_round.edds"
   }
   m_LabelType ENTITYTYPE_DARCMISSIONS
   m_LabelGroupType ENTITYTYPE
  }
 }
}