SCR_PlaceableEntitiesRegistry {
 m_sAddon "DarcMissions"
 m_sSourceDirectory "{79DD690A0F239399}Prefabs/Systems"
 m_Prefabs {
  "{CE7D07A8484A1DE9}Prefabs/Systems/DarcMissionConvoy.et"
  "{003521A6AD7BEB3C}Prefabs/Systems/DarcMissionCrashsite.et"
  "{907DCF8F8818652B}Prefabs/Systems/DarcMissionHunters.et"
  "{922D29EAFA4BB4F1}Prefabs/Systems/DarcMissionOccupation.et"
  "{E8489D032B77CD71}Prefabs/Systems/DarcMissionPatrol.et"
  "{0178274B1C19A219}Prefabs/Systems/DarcMissionSquatters.et"
  "{F1BE2D46F0949F6D}Prefabs/Systems/DarcMissionRoadblock.et"
  "{6A859F436655EEFA}Prefabs/Systems/DarcMissionHvtVip.et"
  "{B9D6798E6A963E0C}Prefabs/Systems/DarcMissionHvtItem.et"
  "{631842AD30537026}Prefabs/Systems/DarcMissionStash.et"
  "{D934E89EF2C4F392}Prefabs/Systems/DarcMissionChopper.et"
 }
}