PersistenceSystemConfig : "{B76E7F1AF7A5D00C}Configs/Systems/Persistence/GameMode/GameMaster.conf" {
 Databases {
  SaveGameDatabase "{6624ADA9A88DA0F6}" {
   Name "DarcDB"
  }
 }
 Storages {
  GamemodeStorage "{66E12C64D9B7705F}" {
   Database "{6624ADA9A88DA0F6}"
  }
 }
}