SCR_EditorAttributeList {
 m_aAttributes {
  SDRC_MissionSubTypeAttribute "{662711F6F752434F}" {
   m_UIInfo SCR_EditorAttributeUIInfo "{662711F6F39D1CF5}" {
    Name "Mission index"
    Description "The sub mission index"
   }
   m_CategoryConfig "{B6275FA75835D59D}Configs/AttributeCategories/DarcMissions.conf"
   m_baseValues SCR_EditorAttributeBaseValues "{662713F970564918}" {
   }
  }
 }
}