SCR_EditorAttributeList : "{F3D6C6D25642352C}Configs/Editor/AttributeLists/Edit.conf" {
 m_aAttributes {
  SDRC_MissionSubTypeAttribute "{662711F6F752434F}" {
   m_UIInfo SCR_EditorAttributeUIInfo "{662711F6F39D1CF5}" {
    Name "Mission index"
    Description "The sub mission index"
   }
   m_CategoryConfig "{B6275FA75835D59D}Configs/AttributeCategories/DarcMissions.conf"
   m_Layout "{680E4985E42137FB}UI/layouts/Editor/Attributes/AttributePrefabs/AttributePrefab_Slider.layout"
   m_baseValues SDRC_MissionSubIdxEditorAttributeBaseValues "{685D1DB11C685668}" {
   }
  }
  SDRC_NonValidAreaAttribute "{685D1DB43B849250}" {
   m_UIInfo SCR_EditorAttributeUIInfo "{685D1DB43B848375}" {
    Name "Radius"
    Description "NonValidArea radius"
   }
   m_CategoryConfig "{B6275FA75835D59D}Configs/AttributeCategories/DarcMissions.conf"
   m_Layout "{680E4985E42137FB}UI/layouts/Editor/Attributes/AttributePrefabs/AttributePrefab_Slider.layout"
   m_baseValues SCR_EditorAttributeBaseValues "{685D1DB43B848300}" {
    m_fMin 50
    m_fMax 1000
    m_fStep 50
    m_iDecimals 0
   }
  }
 }
}