SCR_EditorAttributeList {
 m_aAttributes {
  SDRC_MissionTypeAttribute "{6626F7B6F1C5BB41}" {
   m_UIInfo SCR_EditorAttributeUIInfo "{6626F7B6FDCBCBCC}" {
    Name "Index"
    Description "Index of a sub mission"
   }
   m_CategoryConfig "{B6275FA75835D59D}Configs/AttributeCategories/DarcMissions.conf"
   m_Layout "{680E4985E42137FB}UI/layouts/Editor/Attributes/AttributePrefabs/AttributePrefab_Slider.layout"
   m_baseValues SCR_EditorAttributeBaseValues "{6626F7B68D7176E9}" {
    m_fMin 1
    m_fMax 5
    m_iDecimals 0
   }
  }
 }
}