//------------------------------------------------------------------------------------------------
//! Marker entry which can be placed through map

//NOTE: If you add a new icon, remember to add texture finding to SDRC_IconHelper.GetMarkerTexture
enum SDRC_EMissionIcon
{
	NONE = -1,
	GM_MISSION_X_MAP = 0,
	GM_MISSION_SQUATTERS_MAP,
	GM_MISSION_CRASHSITE_MAP,
	GM_MISSION_OCCUPATION_MAP,
	GM_MISSION_CONVOY_MAP,
	GM_MISSION_HELICOPTER_MAP,
	GM_MISSION_HUNTER_MAP,
	GM_MISSION_PATROL_MAP,
	GM_MISSION_RADIOACTIVE_MAP,
	GM_MISSION_ROADBLOCK_MAP,
	GM_MISSION_HVTVIP_MAP,
	GM_MISSION_HVTITEM_MAP,
	GM_MISSION_STASH_MAP,
	GM_MISSION_BIOHAZARD_MAP,
	GM_MISSION_CRATE_MAP,
	GM_MISSION_DEMON_MAP,
	GM_MISSION_DIAMOND_MAP,
	GM_MISSION_ZOMBIE_MAP,
	RESERVED_18,
	RESERVED_19,
	RESERVED_20,
	RESERVED_21,
	RESERVED_22,
	RESERVED_23,
	RESERVED_24,
	RESERVED_25,
	RESERVED_26,
	RESERVED_27,
	RESERVED_28,
	RESERVED_29,
	RESERVED_30,
	RESERVED_31,
	RESERVED_32,
	RESERVED_33,
	RESERVED_34,
	RESERVED_35,
	RESERVED_36,
	RESERVED_37,
	RESERVED_38,
	RESERVED_39,
	RESERVED_40,
	RESERVED_41,
	RESERVED_42,
	RESERVED_43,
	RESERVED_44,
	RESERVED_45,
	RESERVED_46,
	RESERVED_47,
	
	//Markers to show on top of win/lose mission
	GM_MISSION_WIN_MAP,
	GM_MISSION_LOSE_MAP,
	
	//Other markers
	ICON_DEATHMARKER_MAP,
	ICON_DEATHMARKER_SMALL_MAP,
	ICON_DEATHMARKER_SMALL_RED_MAP,
	ICON_PLUS_SMALL_MAP,
	ICON_EXCLAMATION_SMALL_MAP,
	ICON_CRATE_SMALL_MAP,
	
	//THESE ARE NOT USABLE AS MARKERS
	ICON_WIN_ROUND = 100,
	ICON_LOSE_ROUND,
};

[BaseContainerProps(), SCR_MapMarkerTitle()]
class SDRC_MapMarkerEntryPlaced : SCR_MapMarkerEntryPlaced
{
	//------------------------------------------------------------------------------------------------
	override SCR_EMapMarkerType GetMarkerType()
	{
	 	return SCR_EMapMarkerType.DARC_MISSION;
	}	
}
