SCR_PlaceableEntitiesRegistry {
 m_sAddon "DarcCore"
 m_sSourceDirectory "{79DD690A0F23939A}Prefabs/Systems"
 m_Prefabs {
  "{5CB2D5C0A1519D1B}Prefabs/Systems/DarcMissionConvoy.et"
  "{A6EC23F8EFE0FA02}Prefabs/Systems/DarcMissionCrashsite.et"
  "{7E0E561D682C130F}Prefabs/Systems/DarcMissionHunters.et"
  "{DACB28E580AA22EC}Prefabs/Systems/DarcMissionOccupation.et"
  "{A3299C761A9B2EA4}Prefabs/Systems/DarcMissionPatrol.et"
  "{1CCF5979C8488F09}Prefabs/Systems/DarcMissionSquatters.et"
 }
}