SCR_PlaceableEntitiesRegistry {
 m_sAddon "DarcCore"
 m_sSourceDirectory "{5F387425E3D36113}Prefabs/System"
 m_Prefabs {
  "{5CB2D5C0A1519D1B}Prefabs/System/DarcMissionConvoy.et"
  "{A6EC23F8EFE0FA02}Prefabs/System/DarcMissionCrashsite.et"
  "{7E0E561D682C130F}Prefabs/System/DarcMissionHunters.et"
  "{DACB28E580AA22EC}Prefabs/System/DarcMissionOccupation.et"
  "{A3299C761A9B2EA4}Prefabs/System/DarcMissionPatrol.et"
  "{1CCF5979C8488F09}Prefabs/System/DarcMissionSquatters.et"
 }
}